packages:
  - 'packages/build-configs'
  - 'packages/example'
  - 'packages/http-client'
  - 'packages/http-server'
  - 'packages/spa'
  - 'packages/ts-etl'
  - 'packages/ts-sdk'
  - 'packages/widget'
